/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import Service.Service;
import com.sun.jdi.Value;
import java.awt.BorderLayout;
import java.awt.Graphics2D;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;


import java.awt.Color; 
import java.io.File; 
import java.util.List;

import org.jfree.chart.ChartFactory; 
import org.jfree.chart.ChartUtilities; 
import org.jfree.chart.JFreeChart; 
import org.jfree.chart.plot.PiePlot; 
import org.jfree.data.general.DefaultPieDataset;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.io.File;
import java.util.ArrayList;
import java.util.Locale;

import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import java.util.List;
import org.jfree.chart.block.BlockBorder;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;


/**
 *
 * @author paulh
 */
public class APP extends javax.swing.JFrame {

    /**
     * Creates new form APP
     * @param service
     */
    public APP(Service service) {
        this.service = service;
        initComponents();
        visibleJTXT1(false);
        visibleJTXT(false);
        jLabel30.setVisible(false);
        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel5.setLayout(new java.awt.BorderLayout());
    }
    
    private void visibleJTXT1(boolean var) {
        
        procenttv.setVisible(var);
        procentcv.setVisible(var);
        procenteuro.setVisible(var);
        procenta.setVisible(var);
        procenttva.setVisible(var);
        
        jTextArea2.setVisible(var);   
    }
    
    private void visibleJTXT(boolean var) {
        cantitateField.setVisible(var);
        denumireField.setVisible(var);
        pretIField.setVisible(var);
        pretEField.setVisible(var);
        ziField.setVisible(var);
        lunaField.setVisible(var);
        anField.setVisible(var);
        secundeField.setVisible(var);
        oraField.setVisible(var);
        minuteField.setVisible(var);
        actiuneField.setVisible(var);
        idField.setVisible(var);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPannel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        principalPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        wxit2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        viewPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cantitateField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        denumireField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pretIField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pretEField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ziField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        lunaField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        anField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        secundeField = new javax.swing.JTextField();
        oraField = new javax.swing.JTextField();
        minuteField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        actiuneField = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        statisticsPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        wxit3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        viewPanel1 = new javax.swing.JPanel();
        nameLabel1 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        setingsPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        wxit4 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        procenttv = new javax.swing.JTextField();
        procentcv = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        procenteuro = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        procenta = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        procenttva = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        startPannel.setBackground(new java.awt.Color(3, 252, 177));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hello User");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        exit1.setBackground(new java.awt.Color(255, 255, 255));
        exit1.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        exit1.setForeground(new java.awt.Color(255, 255, 255));
        exit1.setText("X");
        exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout startPannelLayout = new javax.swing.GroupLayout(startPannel);
        startPannel.setLayout(startPannelLayout);
        startPannelLayout.setHorizontalGroup(
            startPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPannelLayout.createSequentialGroup()
                .addContainerGap(406, Short.MAX_VALUE)
                .addGroup(startPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPannelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(347, 347, 347))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPannelLayout.createSequentialGroup()
                        .addComponent(exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        startPannelLayout.setVerticalGroup(
            startPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit1)
                .addGap(197, 197, 197)
                .addComponent(jLabel1)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        principalPanel.setBackground(new java.awt.Color(255, 255, 255));
        principalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(3, 252, 177));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wxit2.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        wxit2.setForeground(new java.awt.Color(255, 255, 255));
        wxit2.setText("X");
        wxit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wxit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wxit2MouseClicked(evt);
            }
        });
        jPanel1.add(wxit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1062, 6, 22, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(String.valueOf((char)171));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 6, 26, 31));

        principalPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 32));

        viewPanel.setBackground(new java.awt.Color(255, 255, 255));
        viewPanel.setForeground(new java.awt.Color(3, 252, 177));
        viewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel.setBackground(new java.awt.Color(255, 153, 0));
        nameLabel.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(204, 204, 204));
        nameLabel.setText("Cuptor cu microunde");
        viewPanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 18, -1, 40));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("STOC:");
        viewPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, -1, 40));

        jSeparator1.setBackground(new java.awt.Color(3, 252, 177));
        jSeparator1.setForeground(new java.awt.Color(3, 252, 177));
        viewPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, 1013, 19));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("5000000");
        viewPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 24, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("CANTITATE:");
        viewPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 18, -1, 40));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("DATA:");
        viewPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 27, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("12:12:2000 12:23:45");
        viewPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 24, -1, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("PRET Int/Ext:");
        viewPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 27, -1, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("250/200 EUR");
        viewPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 24, -1, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(3, 252, 177));
        jLabel10.setText(String.valueOf((char)171));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        viewPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 28, 37));

        jLabel11.setFont(new java.awt.Font("Yu Gothic", 0, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(3, 252, 177));
        jLabel11.setText(String.valueOf((char)187));
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        viewPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 28, 37));

        principalPanel.add(viewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 83, -1, -1));

        jLabel12.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("DENUMIRE");
        principalPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        cantitateField.setBackground(new java.awt.Color(255, 255, 255));
        cantitateField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cantitateField.setForeground(new java.awt.Color(204, 204, 204));
        cantitateField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        principalPanel.add(cantitateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 120, 30));

        jLabel13.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("CANTITATE");
        principalPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        denumireField.setBackground(new java.awt.Color(255, 255, 255));
        denumireField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        denumireField.setForeground(new java.awt.Color(204, 204, 204));
        denumireField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        principalPanel.add(denumireField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 217, 30));

        jLabel14.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("EUR");
        principalPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        jLabel15.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("PRET Intern");
        principalPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        pretIField.setBackground(new java.awt.Color(255, 255, 255));
        pretIField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pretIField.setForeground(new java.awt.Color(204, 204, 204));
        pretIField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        principalPanel.add(pretIField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 120, 30));

        jLabel16.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("buc.");
        principalPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, -1, -1));

        jLabel17.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("PRET Extern");
        principalPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, -1, -1));

        pretEField.setBackground(new java.awt.Color(255, 255, 255));
        pretEField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pretEField.setForeground(new java.awt.Color(204, 204, 204));
        pretEField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        principalPanel.add(pretEField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 120, 30));

        jLabel18.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText(":");
        principalPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 10, -1));

        jLabel20.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("ZI");
        principalPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        ziField.setBackground(new java.awt.Color(255, 255, 255));
        ziField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ziField.setForeground(new java.awt.Color(204, 204, 204));
        ziField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        principalPanel.add(ziField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 60, 30));

        jLabel21.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("LUNA");
        principalPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        lunaField.setBackground(new java.awt.Color(255, 255, 255));
        lunaField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lunaField.setForeground(new java.awt.Color(204, 204, 204));
        lunaField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        principalPanel.add(lunaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 60, 30));

        jLabel22.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("AN");
        principalPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        anField.setBackground(new java.awt.Color(255, 255, 255));
        anField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        anField.setForeground(new java.awt.Color(204, 204, 204));
        anField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        principalPanel.add(anField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 80, 30));

        jLabel23.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("ORA");
        principalPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, -1));

        secundeField.setBackground(new java.awt.Color(255, 255, 255));
        secundeField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        secundeField.setForeground(new java.awt.Color(204, 204, 204));
        secundeField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        principalPanel.add(secundeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 40, 30));

        oraField.setBackground(new java.awt.Color(255, 255, 255));
        oraField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        oraField.setForeground(new java.awt.Color(204, 204, 204));
        oraField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        principalPanel.add(oraField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 40, 30));

        minuteField.setBackground(new java.awt.Color(255, 255, 255));
        minuteField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        minuteField.setForeground(new java.awt.Color(204, 204, 204));
        minuteField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        principalPanel.add(minuteField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 40, 30));

        jLabel24.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("EUR");
        principalPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, -1, -1));

        jLabel25.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText(":");
        principalPanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 10, -1));

        jLabel26.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/icons8_plus_math_40px.png"))); // NOI18N
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        principalPanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 40, 50));

        jLabel27.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/icons8_futures_40px.png"))); // NOI18N
        jLabel27.setText("+");
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        principalPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 40, 50));

        jLabel28.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 204, 204));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/icons8_change_40px.png"))); // NOI18N
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        principalPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 40, 50));

        jLabel29.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/icons8_computer_support_40px_1.png"))); // NOI18N
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        principalPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 40, 50));

        jLabel30.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 204, 204));
        jLabel30.setText("ACTIUNE:");
        principalPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        actiuneField.setBackground(new java.awt.Color(255, 255, 255));
        actiuneField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        actiuneField.setForeground(new java.awt.Color(204, 204, 204));
        actiuneField.setBorder(null);
        principalPanel.add(actiuneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 330, 30));

        jLabel31.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 204, 204));
        jLabel31.setText("ID");
        principalPanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        idField.setBackground(new java.awt.Color(255, 255, 255));
        idField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        idField.setForeground(new java.awt.Color(204, 204, 204));
        idField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        principalPanel.add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 40, 30));

        jLabel54.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(204, 204, 204));
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/icons8_subtract_40px.png"))); // NOI18N
        jLabel54.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel54MouseClicked(evt);
            }
        });
        principalPanel.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 40, 50));

        jLabel56.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(204, 204, 204));
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/icons8_row_40px.png"))); // NOI18N
        jLabel56.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel56MouseClicked(evt);
            }
        });
        principalPanel.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 40, 50));

        statisticsPanel.setBackground(new java.awt.Color(255, 255, 255));
        statisticsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(3, 252, 177));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wxit3.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        wxit3.setForeground(new java.awt.Color(255, 255, 255));
        wxit3.setText("X");
        wxit3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wxit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wxit3MouseClicked(evt);
            }
        });
        jPanel2.add(wxit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1062, 6, 22, -1));

        jLabel19.setFont(new java.awt.Font("Yu Gothic", 1, 25)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(String.valueOf((char)171));
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 6, 26, 31));

        statisticsPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 32));

        viewPanel1.setBackground(new java.awt.Color(255, 255, 255));
        viewPanel1.setForeground(new java.awt.Color(3, 252, 177));
        viewPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel1.setBackground(new java.awt.Color(255, 153, 0));
        nameLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        nameLabel1.setForeground(new java.awt.Color(204, 204, 204));
        nameLabel1.setText(""
        );
        viewPanel1.add(nameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 18, -1, 40));

        jLabel32.setBackground(new java.awt.Color(204, 204, 204));
        jLabel32.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 204, 204));
        jLabel32.setText("STOC:");
        viewPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, -1, 40));

        jSeparator2.setBackground(new java.awt.Color(3, 252, 177));
        jSeparator2.setForeground(new java.awt.Color(3, 252, 177));
        viewPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, 1013, 19));

        jLabel33.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setText("");
        viewPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 24, -1, -1));

        jLabel34.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 204, 204));
        jLabel34.setText("CANTITATE:");
        viewPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 18, -1, 40));

        jLabel37.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 204, 204));
        jLabel37.setText("PRET Int/Ext:");
        viewPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 27, -1, -1));

        jLabel38.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 204, 204));
        jLabel38.setText("");
        viewPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 24, -1, -1));

        statisticsPanel.add(viewPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 83, 690, -1));

        jLabel35.setBackground(new java.awt.Color(204, 204, 204));
        jLabel35.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 204, 204));
        jLabel35.setText("lei");
        statisticsPanel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, 40));

        jLabel36.setBackground(new java.awt.Color(204, 204, 204));
        jLabel36.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 204, 204));
        jLabel36.setText("12345678,95");
        statisticsPanel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, 40));

        jLabel39.setBackground(new java.awt.Color(204, 204, 204));
        jLabel39.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 204, 204));
        jLabel39.setText("VALOARE VAMA");
        statisticsPanel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 40));

        jLabel40.setBackground(new java.awt.Color(204, 204, 204));
        jLabel40.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 204, 204));
        jLabel40.setText("TAXE VAMALE");
        statisticsPanel.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 40));

        jLabel41.setBackground(new java.awt.Color(204, 204, 204));
        jLabel41.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 204, 204));
        jLabel41.setText("12345678,95");
        statisticsPanel.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, 40));

        jLabel42.setBackground(new java.awt.Color(204, 204, 204));
        jLabel42.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 204, 204));
        jLabel42.setText("lei");
        statisticsPanel.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, 40));

        jLabel43.setBackground(new java.awt.Color(204, 204, 204));
        jLabel43.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(204, 204, 204));
        jLabel43.setText("COMISION VAMAL");
        statisticsPanel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 40));

        jLabel44.setBackground(new java.awt.Color(204, 204, 204));
        jLabel44.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(204, 204, 204));
        jLabel44.setText("12345678,95");
        statisticsPanel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, 40));

        jLabel45.setBackground(new java.awt.Color(204, 204, 204));
        jLabel45.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(204, 204, 204));
        jLabel45.setText("lei");
        statisticsPanel.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, 40));

        jLabel46.setBackground(new java.awt.Color(204, 204, 204));
        jLabel46.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(204, 204, 204));
        jLabel46.setText("ACCIZE");
        statisticsPanel.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 40));

        jLabel47.setBackground(new java.awt.Color(204, 204, 204));
        jLabel47.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(204, 204, 204));
        jLabel47.setText("12345678,95");
        statisticsPanel.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, 40));

        jLabel48.setBackground(new java.awt.Color(204, 204, 204));
        jLabel48.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(204, 204, 204));
        jLabel48.setText("lei");
        statisticsPanel.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, 40));

        jLabel49.setBackground(new java.awt.Color(204, 204, 204));
        jLabel49.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(204, 204, 204));
        jLabel49.setText("T.V.A.");
        statisticsPanel.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 40));

        jLabel50.setBackground(new java.awt.Color(204, 204, 204));
        jLabel50.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(204, 204, 204));
        jLabel50.setText("12345678,95");
        statisticsPanel.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, 40));

        jLabel51.setBackground(new java.awt.Color(204, 204, 204));
        jLabel51.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(204, 204, 204));
        jLabel51.setText("lei");
        statisticsPanel.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, 40));

        jSeparator3.setBackground(new java.awt.Color(3, 252, 177));
        jSeparator3.setForeground(new java.awt.Color(3, 252, 177));
        statisticsPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 340, 19));

        jLabel52.setBackground(new java.awt.Color(204, 204, 204));
        jLabel52.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(204, 204, 204));
        jLabel52.setText("12325.25");
        statisticsPanel.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, -1, 40));

        jLabel53.setBackground(new java.awt.Color(204, 204, 204));
        jLabel53.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(204, 204, 204));
        jLabel53.setText("TOTAL");
        statisticsPanel.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, 40));

        jLabel55.setBackground(new java.awt.Color(204, 204, 204));
        jLabel55.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(204, 204, 204));
        jLabel55.setText("lei / buc");
        statisticsPanel.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, -1, 40));

        jLabel58.setBackground(new java.awt.Color(204, 204, 204));
        jLabel58.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(204, 204, 204));
        jLabel58.setText("OBLIGATII VAMA");
        statisticsPanel.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 40));

        jLabel59.setBackground(new java.awt.Color(204, 204, 204));
        jLabel59.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(204, 204, 204));
        jLabel59.setText("123342,56");
        statisticsPanel.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, 40));

        jLabel60.setBackground(new java.awt.Color(204, 204, 204));
        jLabel60.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(204, 204, 204));
        jLabel60.setText("lei/buc");
        statisticsPanel.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, 40));

        jLabel61.setBackground(new java.awt.Color(204, 204, 204));
        jLabel61.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(204, 204, 204));
        jLabel61.setText("PRET VAMA");
        statisticsPanel.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, 40));

        jLabel62.setBackground(new java.awt.Color(204, 204, 204));
        jLabel62.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(204, 204, 204));
        jLabel62.setText("12345678,95");
        statisticsPanel.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, -1, 40));

        jLabel63.setBackground(new java.awt.Color(204, 204, 204));
        jLabel63.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(204, 204, 204));
        jLabel63.setText("lei");
        statisticsPanel.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, -1, 40));

        jSeparator4.setBackground(new java.awt.Color(3, 252, 177));
        jSeparator4.setForeground(new java.awt.Color(3, 252, 177));
        statisticsPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 340, 19));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        statisticsPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 320, 290));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        statisticsPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 310, 290));

        setingsPanel.setBackground(new java.awt.Color(255, 255, 255));
        setingsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(3, 252, 177));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wxit4.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        wxit4.setForeground(new java.awt.Color(255, 255, 255));
        wxit4.setText("X");
        wxit4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wxit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wxit4MouseClicked(evt);
            }
        });
        jPanel3.add(wxit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1062, 6, 22, -1));

        jLabel57.setFont(new java.awt.Font("Yu Gothic", 1, 25)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText(String.valueOf((char)171));
        jLabel57.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel57MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 6, 26, 31));

        setingsPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 32));

        jLabel65.setBackground(new java.awt.Color(204, 204, 204));
        jLabel65.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(204, 204, 204));
        jLabel65.setText(" %");
        setingsPanel.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, 40));

        jLabel66.setBackground(new java.awt.Color(204, 204, 204));
        jLabel66.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(204, 204, 204));
        jLabel66.setText("TAXA VAMALA");
        setingsPanel.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 40));

        jLabel68.setBackground(new java.awt.Color(204, 204, 204));
        jLabel68.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(204, 204, 204));
        jLabel68.setText("COMISION VAMAL");
        setingsPanel.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 40));

        jLabel71.setBackground(new java.awt.Color(204, 204, 204));
        jLabel71.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(204, 204, 204));
        jLabel71.setText("   Salveaza   ");
        jLabel71.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel71.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel71.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel71MouseClicked(evt);
            }
        });
        setingsPanel.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, 40));

        jLabel74.setBackground(new java.awt.Color(204, 204, 204));
        jLabel74.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(204, 204, 204));
        jLabel74.setText("ACCIZA");
        setingsPanel.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 40));

        jLabel77.setBackground(new java.awt.Color(204, 204, 204));
        jLabel77.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(204, 204, 204));
        jLabel77.setText("T.V.A.");
        setingsPanel.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 40));

        procenttv.setBackground(new java.awt.Color(255, 255, 255));
        procenttv.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        procenttv.setForeground(new java.awt.Color(204, 204, 204));
        procenttv.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setingsPanel.add(procenttv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 40, 30));

        procentcv.setBackground(new java.awt.Color(255, 255, 255));
        procentcv.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        procentcv.setForeground(new java.awt.Color(204, 204, 204));
        procentcv.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setingsPanel.add(procentcv, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 40, 30));

        jLabel67.setBackground(new java.awt.Color(204, 204, 204));
        jLabel67.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(204, 204, 204));
        jLabel67.setText(" %");
        setingsPanel.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, 40));

        procenteuro.setBackground(new java.awt.Color(255, 255, 255));
        procenteuro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        procenteuro.setForeground(new java.awt.Color(204, 204, 204));
        procenteuro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setingsPanel.add(procenteuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 70, 30));

        jLabel69.setBackground(new java.awt.Color(204, 204, 204));
        jLabel69.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(204, 204, 204));
        jLabel69.setText(" Lei/Eur");
        setingsPanel.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, 40));

        procenta.setBackground(new java.awt.Color(255, 255, 255));
        procenta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        procenta.setForeground(new java.awt.Color(204, 204, 204));
        procenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setingsPanel.add(procenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 40, 30));

        jLabel70.setBackground(new java.awt.Color(204, 204, 204));
        jLabel70.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(204, 204, 204));
        jLabel70.setText(" %");
        setingsPanel.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, 40));

        procenttva.setBackground(new java.awt.Color(255, 255, 255));
        procenttva.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        procenttva.setForeground(new java.awt.Color(204, 204, 204));
        procenttva.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setingsPanel.add(procenttva, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 40, 30));

        jLabel72.setBackground(new java.awt.Color(204, 204, 204));
        jLabel72.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(204, 204, 204));
        jLabel72.setText(" %");
        setingsPanel.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, 40));

        jLabel73.setBackground(new java.awt.Color(204, 204, 204));
        jLabel73.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(204, 204, 204));
        jLabel73.setText("CURS VALUTAR");
        setingsPanel.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 40));

        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea2.setRows(5);
        jTextArea2.setText("          \n                     Cum se utilizeaza aplicatia");
        jTextArea2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jScrollPane2.setViewportView(jTextArea2);

        setingsPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 430, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(startPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(principalPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(statisticsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(setingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(startPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(statisticsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(setingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit1MouseClicked

    private String setDateString(int pos) {
        String line = String.valueOf(service.showProduse().get(pos).getData());
        return line;
    }
    
    private String dataFrame(String data) {
        String parts[] = data.split("T");
        String d[] = parts[0].split("-");
        String line = d[2]+"-"+d[1]+"-"+d[0]+" "+parts[1];
        return line;
    }
    private String dataFormat(String data1) {
        String parts[] = data1.split(" ");
        String d1[] = parts[0].split("-");
        System.out.println(d1[0]);
        String line = d1[2]+"-"+d1[1]+"-"+d1[0]+"T"+parts[1];
        return line;
    }
    
    private String lunaNumar(String luna) {
        if(luna.equals("JANUARY")) return "01";
        else if(luna.equals("FEBRUARY")) return "02";
        else if(luna.equals("MARCH")) return "03";
        else if(luna.equals("APRIL")) return "04";
        else if(luna.equals("MAY")) return "05";
        else if(luna.equals("JUNE")) return "06";
        else if(luna.equals("JULY")) return "07";
        else if(luna.equals("AUGUST")) return "08";
        else if(luna.equals("SEPTEBER")) return "09";
        else if(luna.equals("OCTOBER")) return "10";
        else if(luna.equals("NOVEMBER")) return "11";
        else if(luna.equals("DECEMBER")) return "12";
        return "";
    }
    
    private void setTextLabelfirst(int pos) {
        int val = service.showProduse().size();
        if(val == 0) {
            nameLabel.setText(" - ");
            jLabel3.setText(" - ");
            jLabel9.setText(" - ");
            jLabel7.setText(" - ");
            
            idField.setText("");
            denumireField.setText("");
            cantitateField.setText("");
            pretIField.setText("");
            pretEField.setText("");
            anField.setText("");
            lunaField.setText("");
            ziField.setText("");
            oraField.setText("");
            minuteField.setText("");
            secundeField.setText("");
            
            nameLabel1.setText("-");
            jLabel33.setText("-");
            jLabel38.setText("-");
            
        }
        else {
            nameLabel.setText(service.showProduse().get(pos).getDenumire());
            jLabel3.setText(String.valueOf(service.showProduse().get(pos).getCantitate()));
            String linePret = String.valueOf((int)service.showProduse().get(pos).getPretInitial()) + "/" + String.valueOf((int)service.showProduse().get(pos).getPretExtern()+" EUR");
            jLabel9.setText(linePret);
            String lineData = dataFrame(setDateString(pos));
            jLabel7.setText(lineData);
            
            idField.setText(String.valueOf(service.getIdByDate(service.showProduse().get(pos).getData())));
            denumireField.setText(service.showProduse().get(pos).getDenumire());
            cantitateField.setText(String.valueOf(service.showProduse().get(pos).getCantitate()));
            pretIField.setText(String.valueOf((int)service.showProduse().get(pos).getPretInitial()));
            pretEField.setText(String.valueOf((int)service.showProduse().get(pos).getPretExtern()));
            anField.setText(String.valueOf(service.showProduse().get(pos).getData().getYear()));
            lunaField.setText(lunaNumar(String.valueOf(service.showProduse().get(pos).getData().getMonth())));
            ziField.setText(String.valueOf(service.showProduse().get(pos).getData().getDayOfMonth()));
            oraField.setText(String.valueOf(service.showProduse().get(pos).getData().getHour()));
            minuteField.setText(String.valueOf(service.showProduse().get(pos).getData().getMinute()));
            secundeField.setText(String.valueOf(service.showProduse().get(pos).getData().getSecond()));
            
            nameLabel1.setText(service.showProduse().get(pos).getDenumire());
            jLabel33.setText(String.valueOf(service.showProduse().get(pos).getCantitate()));
            jLabel38.setText(linePret);
            
            int id = service.getIdByDate(service.showProduse().get(pos).getData());
            jLabel36.setText(String.valueOf(Math.round(service.valoareaVama(id)*100.0)/100.0));
            System.out.println(service.taxeVamale(id));
            jLabel41.setText(String.valueOf(Math.round(service.taxeVamale(id)*100.0)/100.0));
            jLabel44.setText(String.valueOf(Math.round(service.comisioaneVamale(id)*100.0)/100.0));
            jLabel47.setText(String.valueOf(Math.round(service.accize(id)*100.0)/100.0));
            jLabel50.setText(String.valueOf(Math.round(service.tva(id)*100.0)/100.0));
            
            double pretInitial = Math.round((service.taxeVamale(id)+service.comisioaneVamale(id)+service.accize(id)+service.tva(id))/service.showProduse().get(pos).getCantitate()*100.0)/100.0;
            double pretVama = Math.round(service.valoareaVama(id)/service.showProduse().get(pos).getCantitate()*100.0)/100.0;
            double totalBucata = pretInitial + pretVama;
            jLabel59.setText(String.valueOf(pretInitial));
            jLabel62.setText(String.valueOf(pretVama));
            jLabel52.setText(String.valueOf(totalBucata));            
        }
    }
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        startPannel.setVisible(false);
        principalPanel.setVisible(true);
        statisticsPanel.setVisible(false);
        setTextLabelfirst(0);
        visibleJTXT(true);
        visibleJTXT1(false);

//        viewPanel.setVi
    }//GEN-LAST:event_jLabel1MouseClicked

    private void wxit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wxit2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_wxit2MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        principalPanel.setVisible(false);
        startPannel.setVisible(true);
//        statisticsPanel1.setVisible(false);
        visibleJTXT(false);
        visibleJTXT1(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:

        LocalDateTime d = LocalDateTime.parse(dataFormat(jLabel7.getText()));
        int position = 0;
        position = service.getPosition(service.getIdByDate(d));
        position++;
        if(position<=service.showProduse().size()-1)
            setTextLabelfirst(position);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        LocalDateTime d = LocalDateTime.parse(dataFormat(jLabel7.getText()));
        int position = 0;
        position = service.getPosition(service.getIdByDate(d));
        position--;
        if(position>=0)
            setTextLabelfirst(position);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        try {
            // TODO add your handling code here:
            int id = Integer.parseInt(idField.getText());
            String denumire = denumireField.getText();
            int cantitate = Integer.parseInt(cantitateField.getText());
            double pretIntern = Double.parseDouble(pretIField.getText());
            double pretExtern = Double.parseDouble(pretEField.getText());
            String data = anField.getText()+"-"+lunaField.getText()+"-"+ziField.getText()+"T"+oraField.getText()+":"+minuteField.getText()+":"+secundeField.getText();
            LocalDateTime d = LocalDateTime.parse(data);
            
            service.addProdus(id, denumire, cantitate, pretIntern, pretExtern, d);
            jLabel30.setVisible(true);
            actiuneField.setText("Produsul s-a adaugat cu succes");
            
            int position = 0;
            position = service.getPosition(service.getIdByDate(d));
            setTextLabelfirst(position);
            
        } catch (Exception ex) {
            Logger.getLogger(APP.class.getName()).log(Level.SEVERE, null, ex);
            actiuneField.setText("Eroare la adaugarea produsului");
        }

        
    }//GEN-LAST:event_jLabel26MouseClicked

      private double procent1() {
        double obligatii = Double.parseDouble(jLabel59.getText());
        double valoare = Double.parseDouble(jLabel62.getText());   
        double procent = obligatii/(valoare/100);

        return Math.round(procent*100.0)/100.0;        
    }
    
    private double procent2() {
        double obligatii = Double.parseDouble(jLabel59.getText());
        double pret = Double.parseDouble(jLabel52.getText());
        double procent = obligatii/(pret/100);

        return Math.round(procent*100.0)/100.0;        
    }
    
    private void pie1() {
        DefaultPieDataset dataset = new DefaultPieDataset(); 
        JFreeChart chart; 
        
        // Defining the dataset 
        System.out.println(procent1());
                System.out.println(procent2());

        dataset.setValue("Windows", procent1()); 
        dataset.setValue("DOS", 100-procent1()); 
        
        chart = ChartFactory.createPieChart3D("OS Chart", dataset, true, false, false); 
        chart.setBorderVisible(false); // set border invisible chart
        chart.getLegend().setFrame(BlockBorder.NONE); // set border invisible legend
        
        PiePlot3D plot = (PiePlot3D)chart.getPlot(); 
        plot.setBackgroundPaint(Color.WHITE); // set color white to background
        plot.setLabelGenerator(null); // set no labels
        plot.setOutlinePaint(null); // set no border chart
       
         class PieRenderer 
    { 
        private Color[] color; 
        
        public PieRenderer(Color[] color) 
        { 
            this.color = color; 
        }        
        
        public void setColor(PiePlot plot, DefaultPieDataset dataset) 
        { 
            List <Comparable> keys = dataset.getKeys(); 
            int aInt; 
            
            for (int i = 0; i < keys.size(); i++) 
            { 
                aInt = i % this.color.length; 
                plot.setSectionPaint(keys.get(i), this.color[aInt]); 
            } 
        }

    }
 
        // Specify the colors here 
        Color color1 = new Color(3,252,177);
        Color color2 = new Color(255,255,255);
        Color[] colors = {color1,color2}; 
        PieRenderer renderer = new PieRenderer(colors); 
        renderer.setColor(plot, dataset); 
        
        ChartPanel chartPanel1 = new ChartPanel(chart);
        jPanel4.removeAll();        // clear panel before add new chart
        jPanel4.add(chartPanel1, BorderLayout.CENTER);
        jPanel4.validate(); 

    }
    
    private void pie2() {
           DefaultPieDataset dataset1 = new DefaultPieDataset(); 
        JFreeChart chart1; 
        
        // Defining the dataset 
        System.out.println(procent1());
                System.out.println(procent2());

        dataset1.setValue("Windows", procent2()); 
        dataset1.setValue("DOS", 100-procent2()); 
        
        chart1 = ChartFactory.createPieChart3D("OS Chart", dataset1, true, false, false); 
        chart1.setBorderVisible(false); // set border invisible chart
        chart1.getLegend().setFrame(BlockBorder.NONE); // set border invisible legend
        
        PiePlot3D plot1 = (PiePlot3D)chart1.getPlot(); 
        plot1.setBackgroundPaint(Color.WHITE); // set color white to background
        plot1.setLabelGenerator(null); // set no labels
        plot1.setOutlinePaint(null); // set no border chart
       
         class PieRenderer1 
    { 
        private Color[] color; 
        
        public PieRenderer1(Color[] color) 
        { 
            this.color = color; 
        }        
        
        public void setColor(PiePlot plot, DefaultPieDataset dataset) 
        { 
            List <Comparable> keys = dataset.getKeys(); 
            int aInt; 
            
            for (int i = 0; i < keys.size(); i++) 
            { 
                aInt = i % this.color.length; 
                plot.setSectionPaint(keys.get(i), this.color[aInt]); 
            } 
        }

    }
 
        // Specify the colors here 
        Color color1 = new Color(3,252,177);
        Color color2 = new Color(255,255,255);
        Color[] colors = {color1,color2}; 
        PieRenderer1 renderer1 = new PieRenderer1(colors); 
        renderer1.setColor(plot1, dataset1); 
        
        ChartPanel chartPanel11 = new ChartPanel(chart1);
        jPanel5.removeAll();        // clear panel before add new chart
        jPanel5.add(chartPanel11, BorderLayout.CENTER);
        jPanel5.validate(); 

    }

    
    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        
        String data = anField.getText()+"-"+lunaField.getText()+"-"+ziField.getText()+"T"+oraField.getText()+":"+minuteField.getText()+":"+secundeField.getText();
        LocalDateTime d = LocalDateTime.parse(data);
            
        int position = 0;
        position = service.getPosition(service.getIdByDate(d));
        setTextLabelfirst(position);
        
     
        
        
        
        principalPanel.setVisible(false);
        statisticsPanel.setVisible(true);
//        statisticsPanel1.setVisible(false);
        
        //_____________________________________________________________________
        pie1();
        pie2();   

    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        try {
            // TODO add your handling code here:
            int id = Integer.parseInt(idField.getText());
            String denumire = denumireField.getText();
            int cantitate = Integer.parseInt(cantitateField.getText());
            double pretIntern = Double.parseDouble(pretIField.getText());
            double pretExtern = Double.parseDouble(pretEField.getText());
            String data = anField.getText()+"-"+lunaField.getText()+"-"+ziField.getText()+"T"+oraField.getText()+":"+minuteField.getText()+":"+secundeField.getText();
            LocalDateTime d = LocalDateTime.parse(data);
            
            service.updateProdus(id, denumire, cantitate, pretIntern, pretExtern, d);
            jLabel30.setVisible(true);
            actiuneField.setText("Produsul s-a modificat cu succes");
            
            int position = 0;
            position = service.getPosition(service.getIdByDate(d));
            setTextLabelfirst(position);
            
        } catch (Exception ex) {
            Logger.getLogger(APP.class.getName()).log(Level.SEVERE, null, ex);
            actiuneField.setText("Eroare la modificarea produsului");
        }
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        startPannel.setVisible(false);
        principalPanel.setVisible(false);
        statisticsPanel.setVisible(false);
        setingsPanel.setVisible(true);
        
        
        procenttv.setText(String.valueOf(service.getTaxaVamala()));
        procentcv.setText(String.valueOf(service.getComisionVamal()));
        procenteuro.setText(String.valueOf(service.getCursValutar()));
        procenta.setText(String.valueOf(service.getAcciza()));
        procenttva.setText(String.valueOf(service.getTva()));
        
        visibleJTXT(false);
        visibleJTXT1(true);

    }//GEN-LAST:event_jLabel29MouseClicked

    private void wxit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wxit3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_wxit3MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        
        
        principalPanel.setVisible(true);
        statisticsPanel.setVisible(false);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel54MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel54MouseClicked

    private void jLabel56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel56MouseClicked
        // TODO add your handling code here:
        idField.setText("");
        denumireField.setText("");
        cantitateField.setText("");
        pretIField.setText("");
        pretEField.setText("");
        anField.setText("");
        lunaField.setText("");
        ziField.setText("");
        oraField.setText("");
        minuteField.setText("");
        secundeField.setText("");
        
    }//GEN-LAST:event_jLabel56MouseClicked

    private void wxit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wxit4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_wxit4MouseClicked

    private void jLabel57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseClicked
        // TODO add your handling code here:
        startPannel.setVisible(false);
        principalPanel.setVisible(true);
        statisticsPanel.setVisible(false);
        setingsPanel.setVisible(false);
        
        visibleJTXT(true);
        visibleJTXT1(false);
        
    }//GEN-LAST:event_jLabel57MouseClicked

    private void jLabel71MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel71MouseClicked
        // TODO add your handling code here:
        
        service.setTaxaVamala(Double.parseDouble(procenttv.getText()));
        service.setComisionVamal(Double.parseDouble(procentcv.getText()));
        service.setCursValutar(Double.parseDouble(procenteuro.getText()));
        service.setAcciza(Double.parseDouble(procenta.getText()));
        service.setTva(Double.parseDouble(procenttva.getText()));
        
        System.out.println(service.getTaxaVamala());
    }//GEN-LAST:event_jLabel71MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APP(service).setVisible(true);
            }
        });
    }
    
    private static Service service;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actiuneField;
    private javax.swing.JTextField anField;
    private javax.swing.JTextField cantitateField;
    private javax.swing.JTextField denumireField;
    private javax.swing.JLabel exit1;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField lunaField;
    private javax.swing.JTextField minuteField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JTextField oraField;
    private javax.swing.JTextField pretEField;
    private javax.swing.JTextField pretIField;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JTextField procenta;
    private javax.swing.JTextField procentcv;
    private javax.swing.JTextField procenteuro;
    private javax.swing.JTextField procenttv;
    private javax.swing.JTextField procenttva;
    private javax.swing.JTextField secundeField;
    private javax.swing.JPanel setingsPanel;
    private javax.swing.JPanel startPannel;
    private javax.swing.JPanel statisticsPanel;
    private javax.swing.JPanel viewPanel;
    private javax.swing.JPanel viewPanel1;
    private javax.swing.JLabel wxit2;
    private javax.swing.JLabel wxit3;
    private javax.swing.JLabel wxit4;
    private javax.swing.JTextField ziField;
    // End of variables declaration//GEN-END:variables
}
